### ISSUE TITLE
No Audio out of speaker

### ISSUE THREAD

**Issue by dcallahanjr** [Microsemi/ZLK38AVS#7]
I recently (last week) updated my raspberry Pi3 board with the latest Stretch OS and reinstalled the ZLK38AVS software. Everything is working except i do not hear any speech output on the speaker. I noticed there are ALSA errors when I first start the AVS Demo (see below). I originally had this running fine on the Jessie image but figured I would update to the latest Pi and AVS version.

Also, I ran a test "speaker-test -c2 -twav" which ran successfully so I know the hardware and speaker are still good. 

Any thoughts? 

###################################################################
###################################################################
"/etc/asound.conf"

pcm.dmixed {
    ipc_key 1025
    type dmix
    slave {
        pcm "hw:sndmicrosemidac,0"
        channels 2
        rate 48000
    }
}

pcm.dsnooped {
    ipc_key 1027
    type dsnoop
    slave {
        pcm "hw:sndmicrosemidac,0"
        channels 1
        rate 48000
    }
}

pcm.asymed {
    type asym
    playback.pcm "dmixed"
    capture.pcm "dsnooped"
}

pcm.!default {
    type plug
    slave.pcm "asymed"
}

ctl.!default {
    type hw
    card sndmicrosemidac
}

###################################################################
###################################################################
"~/.asoundrc"

pcm.dmixed {
    ipc_key 1025
    type dmix
    slave {
        pcm "hw:sndmicrosemidac,0"
        channels 2
        rate 48000
    }
}

pcm.dsnooped {
    ipc_key 1027
    type dsnoop
    slave {
        pcm "hw:sndmicrosemidac,0"
        channels 1
        rate 48000
    }
}

pcm.asymed {
    type asym
    playback.pcm "dmixed"
    capture.pcm "dsnooped"
}

pcm.!default {
    type plug
    slave.pcm "asymed"
}

ctl.!default {
    type hw
    card sndmicrosemidac
}

###################################################################
###################################################################

pi@raspberrypi:~/Microsemi/ZLK38AVS $ make start_alexa
#############################
#       Connecting...       #
#############################

########################################
#       Alexa is currently idle!       #
########################################

ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

############################
#       Listening...       #
############################

###########################
#       Thinking...       #
###########################

###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

**Comment by dcallahanjr** [comment]
In addition, I'm using the 3.5mm Speaker jack on the ZLE38AVS board. When I reinstalled the software I followed Version 3.0 of the ZLK38AVS User Guide.

**Comment by sdumorti** [comment]
Hi @dcallahanjr ,

We have issues with the latest Raspbian Strech image because the default audio sink is not ALSA anymore. You have to use [Raspbian Stretch 2017-09-07](http://downloads.raspberrypi.org/raspbian/images/raspbian-2017-09-08/2017-09-07-raspbian-stretch.zip).
We just updated our [wiki](https://github.com/Microsemi/ZLK38AVS/wiki) and added a [Troubleshooting](https://github.com/Microsemi/ZLK38AVS/wiki/Troubleshooting#troubleshooting) section and more detailed instructions.
I recommend that you use the ready made [image](https://github.com/Microsemi/ZLK38AVS/wiki/Software_Installation#software-installation)

**Comment by dcallahanjr** [comment]
Great thank you for the feedback.
